name: Link Checker

on:
  schedule:
    - cron: '0 0 * * 0' # Weekly on Sundays
  workflow_dispatch:
  push:
    branches: ["master", "main"]

jobs:
  linkChecker:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.9.0
        with:
          args: --verbose --no-progress --exclude 'https://www.linkedin.com/.*' --exclude 'https://www.instagram.com/.*' --exclude '.*\{\{.*' './**/*.md' './**/*.html'
          fail: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
